#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Hossein Aarabi"
email = "haarabi@centerfield.com"

[ui]
editor = "nvim"
diff-editor = ":builtin"
default-command = "log"

[git]
push-bookmark-prefix = "haarabi/push-"

[colors]
"commit_id prefix" = "bright blue"
"change_id prefix" = "bright magenta"
"bookmarks local" = "cyan"
"bookmarks remote" = "bright cyan"
working_copy = { bg = "default", fg = "bright cyan", bold = true }
"diff added" = "green"
"diff removed" = "red"
"diff modified" = "yellow"
"description placeholder" = "red"

[remotes.origin]
auto-track-bookmarks = "*"
